using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace prohpharmacy_trekking_app.Migrations
{
    /// <inheritdoc />
    public partial class AddCustomerLedgerEntries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CustomerLedgerEntries",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CustomerAccountId = table.Column<Guid>(type: "uuid", nullable: false),
                    EntryType = table.Column<string>(type: "character varying(10)", maxLength: 10, nullable: false),
                    Amount = table.Column<decimal>(type: "numeric(14,2)", precision: 14, scale: 2, nullable: false),
                    Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
                    TrekkingTripId = table.Column<Guid>(type: "uuid", nullable: true),
                    TrekkingTripStopId = table.Column<Guid>(type: "uuid", nullable: true),
                    IsAutoGenerated = table.Column<bool>(type: "boolean", nullable: false),
                    RecordedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    CreatedByStaffId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CustomerLedgerEntries", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CustomerLedgerEntries_CustomerAccounts_CustomerAccountId",
                        column: x => x.CustomerAccountId,
                        principalTable: "CustomerAccounts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CustomerLedgerEntries_StaffMembers_CreatedByStaffId",
                        column: x => x.CreatedByStaffId,
                        principalTable: "StaffMembers",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CustomerLedgerEntries_TrekkingTripStops_TrekkingTripStopId",
                        column: x => x.TrekkingTripStopId,
                        principalTable: "TrekkingTripStops",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                    table.ForeignKey(
                        name: "FK_CustomerLedgerEntries_TrekkingTrips_TrekkingTripId",
                        column: x => x.TrekkingTripId,
                        principalTable: "TrekkingTrips",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.SetNull);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CustomerLedgerEntries_CreatedByStaffId",
                table: "CustomerLedgerEntries",
                column: "CreatedByStaffId");

            migrationBuilder.CreateIndex(
                name: "IX_CustomerLedgerEntries_CustomerAccountId",
                table: "CustomerLedgerEntries",
                column: "CustomerAccountId");

            migrationBuilder.CreateIndex(
                name: "IX_CustomerLedgerEntries_RecordedAt",
                table: "CustomerLedgerEntries",
                column: "RecordedAt");

            migrationBuilder.CreateIndex(
                name: "IX_CustomerLedgerEntries_TrekkingTripId",
                table: "CustomerLedgerEntries",
                column: "TrekkingTripId");

            migrationBuilder.CreateIndex(
                name: "IX_CustomerLedgerEntries_TrekkingTripStopId_IsAutoGenerated",
                table: "CustomerLedgerEntries",
                columns: new[] { "TrekkingTripStopId", "IsAutoGenerated" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CustomerLedgerEntries");
        }
    }
}
