using Carter;
using MediatR;
using Microsoft.EntityFrameworkCore;
using prohpharmacy_trekking_app.Database;
using prohpharmacy_trekking_app.Extensions;
using prohpharmacy_trekking_app.Features.Fleet.Entities;
using prohpharmacy_trekking_app.Features.Fleet.Enums;
using prohpharmacy_trekking_app.Features.Ledger.Entities;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Features.Trekking.Enums;
using prohpharmacy_trekking_app.Providers;
using prohpharmacy_trekking_app.Shared;

namespace prohpharmacy_trekking_app.Features.Trekking;

public static class ApproveReturn
{
    public class Command : IRequest<Result<ApprovalResponse>>
    {
        public Guid ReturnId { get; set; }
    }

    public class ApprovalResponse
    {
        public Guid ReturnId { get; set; }
        public string InvoiceNumber { get; set; } = string.Empty;
        public string ProductName { get; set; } = string.Empty;
        public decimal RefundAmount { get; set; }
        public string ApprovalStatus { get; set; } = string.Empty;
        public DateTime ApprovedAt { get; set; }
    }

    internal sealed class Handler(AppDbContext db, AuthProvider auth)
        : IRequestHandler<Command, Result<ApprovalResponse>>
    {
        public async Task<Result<ApprovalResponse>> Handle(Command request, CancellationToken cancellationToken)
        {
            var ret = await db.TrekkingTripStopReturns
                .Include(r => r.SaleInvoice)
                .Include(r => r.Product)
                .Include(r => r.TrekkingTripStop)
                    .ThenInclude(s => s.TrekkingTrip)
                .FirstOrDefaultAsync(r => r.Id == request.ReturnId, cancellationToken);

            if (ret is null)
                return Result.Failure<ApprovalResponse>(Error.CreateNotFoundError("Return not found."));

            if (ret.ApprovalStatus != ReturnApprovalStatus.Pending)
                return Result.Failure<ApprovalResponse>(Error.BadRequest($"Return is already {ret.ApprovalStatus}."));

            if (!Guid.TryParse(auth.GetStaffId(), out var staffId))
                return Result.Failure<ApprovalResponse>(
                    Error.BadRequest("Authenticated staff identity is missing or invalid."));

            ret.ApprovalStatus = ReturnApprovalStatus.Approved;
            ret.ApprovedByStaffId = staffId;
            ret.ApprovedAt = DateTime.UtcNow;

            var ledgerEntry = new CustomerLedgerEntry
            {
                CustomerAccountId = ret.SaleInvoice.CustomerAccountId,
                TrekkingTripId = ret.TrekkingTripStop.TrekkingTripId,
                TrekkingTripStopId = ret.TrekkingTripStopId,
                EntryType = LedgerEntryType.Credit,
                Amount = ret.RefundAmount ?? 0,
                Description = $"Return approved — Invoice {ret.SaleInvoice.InvoiceNumber}, {ret.Product.Name}",
                PaymentMethod = ret.RefundMethod?.ToString(),
                IsAutoGenerated = true,
                CreatedByStaffId = staffId,
                RecordedAt = DateTime.UtcNow,
                CreatedAt = DateTime.UtcNow
            };

            db.CustomerLedgerEntries.Add(ledgerEntry);

            var vehicleStock = await db.VehicleProductStocks
                .FirstOrDefaultAsync(s =>
                    s.VehicleId == ret.TrekkingTripStop.TrekkingTrip.VehicleId &&
                    s.ProductId == ret.ProductId, cancellationToken);

            if (vehicleStock is not null)
            {
                vehicleStock.BasicQuantityOnHand += ret.BasicQtyReturned;
                vehicleStock.PackagingQuantityOnHand += ret.PackagingQtyReturned ?? 0;
                vehicleStock.UpdatedAt = DateTime.UtcNow;

                db.VehicleStockLedger.Add(new VehicleStockLedger
                {
                    VehicleId = ret.TrekkingTripStop.TrekkingTrip.VehicleId,
                    ProductId = ret.ProductId,
                    ChangeType = StockChangeType.Addition,
                    Source = StockChangeSource.ReturnApproval,
                    BasicQtyChange = ret.BasicQtyReturned,
                    PackagingQtyChange = ret.PackagingQtyReturned ?? 0,
                    BasicBalanceAfter = vehicleStock.BasicQuantityOnHand,
                    PackagingBalanceAfter = vehicleStock.PackagingQuantityOnHand,
                    Reason = $"Return approved — Invoice {ret.SaleInvoice.InvoiceNumber}, {ret.Product.Name}",
                    ReferenceId = ret.Id,
                    AuthorStaffId = staffId,
                    RecordedAt = DateTime.UtcNow
                });
            }

            await db.SaveChangesAsync(cancellationToken);

            return Result.Success(new ApprovalResponse
            {
                ReturnId = ret.Id,
                InvoiceNumber = ret.SaleInvoice.InvoiceNumber ?? string.Empty,
                ProductName = ret.Product.Name,
                RefundAmount = ret.RefundAmount ?? 0,
                ApprovalStatus = ret.ApprovalStatus.ToString(),
                ApprovedAt = ret.ApprovedAt!.Value
            });
        }
    }
}

public class ApproveReturnEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapPost("api/v1/returns/{returnId:guid}/approve",
            async (Guid returnId, ISender sender) =>
            {
                var result = await sender.Send(new ApproveReturn.Command { ReturnId = returnId });
                return result.IsFailure
                    ? Results.UnprocessableEntity(result.Error)
                    : Results.Ok(result.Value);
            })
        .WithTags("Trekking")
        .WithGroupName(SwaggerDoc.SwaggerEndpointDefinitions.Trekking)
        .WithSummary("Approve a pending product return")
        .WithDescription("Approves the return and creates a credit ledger entry for the refund amount.")
        .Produces<ApproveReturn.ApprovalResponse>(200)
        .Produces<Error>(404)
        .Produces<Error>(422)
        .RequireAuthorization();
    }
}
