using Carter;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using prohpharmacy_trekking_app.Database;
using prohpharmacy_trekking_app.Extensions;
using prohpharmacy_trekking_app.Features.Ledger.Entities;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Features.Trekking.Enums;
using prohpharmacy_trekking_app.Shared;
using static prohpharmacy_trekking_app.Features.Trekking.CreateTrek;

namespace prohpharmacy_trekking_app.Features.Trekking;

public static class ChangeTrekStatus
{
    public class Command : IRequest<Result<TrekResponse>>
    {
        public Guid Id { get; set; }
        public TrekStatus Status { get; set; }
    }

    public class Validator : AbstractValidator<Command>
    {
        public Validator()
        {
            RuleFor(x => x.Status).IsInEnum();
        }
    }

    internal sealed class Handler : IRequestHandler<Command, Result<TrekResponse>>
    {
        private readonly AppDbContext _db;
        private readonly IValidator<Command> _validator;

        public Handler(AppDbContext db, IValidator<Command> validator)
        {
            _db = db;
            _validator = validator;
        }

        public async Task<Result<TrekResponse>> Handle(Command request, CancellationToken cancellationToken)
        {
            var validation = await _validator.ValidateAsync(request, cancellationToken);
            if (!validation.IsValid)
                return Result.Failure<TrekResponse>(Error.ValidationError(validation));

            await using var transaction = await _db.Database.BeginTransactionAsync(cancellationToken);
            try
            {
                var trip = await _db.TrekkingTrips
                    .Include(t => t.Branch)
                    .Include(t => t.Driver)
                    .Include(t => t.Vehicle)
                    .Include(t => t.Stops)
                        .ThenInclude(s => s.Products)
                    .FirstOrDefaultAsync(t => t.Id == request.Id, cancellationToken);

                if (trip is null)
                    return Result.Failure<TrekResponse>(Error.CreateNotFoundError("Trekking trip not found."));

                trip.Status = request.Status;
                trip.UpdatedAt = DateTime.UtcNow;

                if (request.Status == TrekStatus.Completed)
                    await SyncLedgerOnCompletionAsync(trip, cancellationToken);
                else if (request.Status == TrekStatus.Cancelled)
                    await ClearTrekLedgerEntriesAsync(trip.Id, cancellationToken);

                await _db.SaveChangesAsync(cancellationToken);
                await transaction.CommitAsync(cancellationToken);

                return Result.Success(CreateTrek.Handler.ToResponse(
                    trip,
                    trip.Branch?.Name ?? string.Empty,
                    trip.Driver?.FullName ?? string.Empty,
                    trip.Vehicle?.DisplayName ?? string.Empty,
                    []));
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        private async Task SyncLedgerOnCompletionAsync(Entities.TrekkingTrip trip, CancellationToken cancellationToken)
        {
            var stopIds = trip.Stops.Select(s => s.Id).ToList();

            var existing = await _db.CustomerLedgerEntries
                .Where(e => e.TrekkingTripStopId.HasValue
                    && stopIds.Contains(e.TrekkingTripStopId.Value)
                    && e.IsAutoGenerated)
                .ToListAsync(cancellationToken);
            _db.CustomerLedgerEntries.RemoveRange(existing);

            var now = DateTime.UtcNow;
            foreach (var stop in trip.Stops)
            {
                var paymentGroups = stop.Products
                    .Where(p => p.AmtPaid > 0 && p.PaymentMethod.HasValue)
                    .GroupBy(p => p.PaymentMethod!.Value);

                foreach (var group in paymentGroups)
                {
                    var amtPaid = group.Sum(p => p.AmtPaid ?? 0);
                    _db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Credit,
                        Amount = amtPaid,
                        PaymentMethod = group.Key.ToString(),
                        Description = $"Payment received ({group.Key}) — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = trip.DriverStaffId,
                        CreatedAt = now
                    });
                }

                var balance = stop.Products.Sum(p => p.Balance ?? 0);
                if (balance > 0)
                    _db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Debit,
                        Amount = balance,
                        Description = $"Outstanding balance — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = trip.DriverStaffId,
                        CreatedAt = now
                    });
            }
        }

        private async Task ClearTrekLedgerEntriesAsync(Guid trekId, CancellationToken cancellationToken)
        {
            var existing = await _db.CustomerLedgerEntries
                .Where(e => e.TrekkingTripId == trekId && e.IsAutoGenerated)
                .ToListAsync(cancellationToken);
            _db.CustomerLedgerEntries.RemoveRange(existing);
        }
    }
}

public class ChangeTrekStatusEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapPatch("api/v1/treks/{id:guid}/status", async (Guid id, ChangeTrekStatus.Command command, ISender sender) =>
        {
            command.Id = id;
            var result = await sender.Send(command);
            return result.IsFailure
                ? Results.UnprocessableEntity(result.Error)
                : Results.Ok(result.Value);
        })
        .WithTags("Trekking")
        .WithGroupName(SwaggerDoc.SwaggerEndpointDefinitions.Trekking)
        .WithSummary("Change the status of a trekking trip")
        .WithDescription("Valid statuses: Draft, Scheduled, InProgress, Completed, Cancelled.")
        .Produces<TrekResponse>(200)
        .Produces<Error>(404)
        .Produces<Error>(422)
        .RequireAuthorization();
    }
}
