using Carter;
using MediatR;
using Microsoft.EntityFrameworkCore;
using prohpharmacy_trekking_app.Database;
using prohpharmacy_trekking_app.Extensions;
using prohpharmacy_trekking_app.Features.Ledger.Entities;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Features.Trekking.Enums;
using prohpharmacy_trekking_app.Features.Fleet.Entities;
using prohpharmacy_trekking_app.Features.Fleet.Enums;
using prohpharmacy_trekking_app.Services.Email;
using prohpharmacy_trekking_app.Services.Push;
using prohpharmacy_trekking_app.Shared;
using static prohpharmacy_trekking_app.Features.Trekking.CreateTrek;

namespace prohpharmacy_trekking_app.Features.Trekking;

public static class CompleteTrekByDriverToken
{
    public class Command : IRequest<Result<TrekResponse>>
    {
        public Guid Token { get; set; }
    }

    internal sealed class Handler(AppDbContext db, NotificationDispatcher notifications, IEmailService email, IConfiguration config) : IRequestHandler<Command, Result<TrekResponse>>
    {
        public async Task<Result<TrekResponse>> Handle(Command request, CancellationToken cancellationToken)
        {
            await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken);
            try
            {
                var trip = await db.TrekkingTrips
                    .Include(t => t.Region)
                    .Include(t => t.Branch)
                    .Include(t => t.Driver)
                    .Include(t => t.SalesStaff)
                    .Include(t => t.Vehicle)
                    .Include(t => t.Stops)
                        .ThenInclude(s => s.Products)
                    .Include(t => t.Stops)
                        .ThenInclude(s => s.Returns)
                    .FirstOrDefaultAsync(t => t.DriverToken == request.Token, cancellationToken);

                if (trip is null)
                    return Result.Failure<TrekResponse>(Error.CreateNotFoundError("Trek not found. The token may be invalid."));

                if (trip.Status == TrekStatus.Completed)
                    return Result.Failure<TrekResponse>(Error.BadRequest("This trek is already marked as completed."));

                if (trip.Status == TrekStatus.Cancelled)
                    return Result.Failure<TrekResponse>(Error.BadRequest("A cancelled trek cannot be completed."));

                if (trip.Status != TrekStatus.InProgress)
                    return Result.Failure<TrekResponse>(Error.BadRequest("Only an in-progress trek can be marked as completed."));

                trip.Status = TrekStatus.Completed;
                trip.UpdatedAt = DateTime.UtcNow;

                await SyncLedgerOnCompletionAsync(trip, cancellationToken);
                await CaptureStockSnapshotAsync(trip, cancellationToken);
                await SyncVehicleStockOnCompletionAsync(trip, cancellationToken);

                await db.SaveChangesAsync(cancellationToken);
                await transaction.CommitAsync(cancellationToken);

                await NotifyPendingReturnsAsync(trip, cancellationToken);

                return Result.Success(CreateTrek.Handler.ToResponse(
                    trip,
                    trip.Region?.Name ?? string.Empty,
                    trip.Branch?.Name,
                    trip.Driver?.FullName ?? string.Empty,
                    trip.SalesStaff?.FullName,
                    trip.Vehicle?.DisplayName ?? string.Empty,
                    []));
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        private async Task SyncLedgerOnCompletionAsync(Entities.TrekkingTrip trip, CancellationToken cancellationToken)
        {
            var stopIds = trip.Stops.Select(s => s.Id).ToList();

            var existing = await db.CustomerLedgerEntries
                .Where(e => e.TrekkingTripStopId.HasValue
                    && stopIds.Contains(e.TrekkingTripStopId.Value)
                    && e.IsAutoGenerated)
                .ToListAsync(cancellationToken);
            db.CustomerLedgerEntries.RemoveRange(existing);

            var invoiceNumbersByStop = await db.SaleInvoices
                .Where(i => stopIds.Contains(i.TrekkingTripStopId) && i.InvoiceNumber != null)
                .ToDictionaryAsync(i => i.TrekkingTripStopId, i => i.InvoiceNumber!, cancellationToken);

            var now = DateTime.UtcNow;
            var attributedStaffId = trip.SalesStaffId ?? trip.DriverStaffId;

            foreach (var stop in trip.Stops)
            {
                var stopTotal = stop.Products.Sum(p =>
                    p.AmountDue ?? ((p.AmtPaid ?? 0) + (p.Balance ?? 0)));
                invoiceNumbersByStop.TryGetValue(stop.Id, out var invoiceNumber);

                if (stopTotal > 0)
                    db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Debit,
                        Amount = stopTotal,
                        Description = invoiceNumber is not null
                            ? $"Invoice {invoiceNumber} — Goods delivered (Trek {trip.TrekNumber})"
                            : $"Goods delivered — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = attributedStaffId,
                        CreatedAt = now
                    });

                var paymentGroups = stop.Products
                    .Where(p => p.AmtPaid > 0 && p.PaymentMethod.HasValue)
                    .GroupBy(p => p.PaymentMethod!.Value);

                foreach (var group in paymentGroups)
                {
                    var amtPaid = group.Sum(p => p.AmtPaid ?? 0);
                    db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Credit,
                        Amount = amtPaid,
                        PaymentMethod = group.Key.ToString(),
                        Description = invoiceNumber is not null
                            ? $"Invoice {invoiceNumber} — Payment received: {group.Key} (Trek {trip.TrekNumber})"
                            : $"Payment received ({group.Key}) — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = attributedStaffId,
                        CreatedAt = now
                    });
                }
            }
        }

        private Task CaptureStockSnapshotAsync(Entities.TrekkingTrip trip, CancellationToken cancellationToken) =>
            CaptureStockSnapshotAsync(db, trip, cancellationToken);

        internal static async Task CaptureStockSnapshotAsync(AppDbContext db, Entities.TrekkingTrip trip, CancellationToken cancellationToken)
        {
            var alreadyCaptured = await db.TrekkingTripStockSnapshots
                .AnyAsync(s => s.TrekkingTripId == trip.Id, cancellationToken);
            if (alreadyCaptured) return;

            var soldByProduct = trip.Stops
                .SelectMany(s => s.Products)
                .GroupBy(p => p.ProductId)
                .ToDictionary(g => g.Key, g => new
                {
                    BasicSold = g.Sum(p => p.BasicQtyDelivered ?? 0),
                    PackagingSold = g.Sum(p => p.PackagingQtyDelivered ?? 0),
                    Revenue = g.Sum(p => p.AmountDue ?? ((p.AmtPaid ?? 0) + (p.Balance ?? 0)))
                });

            var loadedProductIds = await db.TrekStockLoads
                .Where(l => l.TrekkingTripId == trip.Id)
                .Select(l => l.ProductId)
                .ToListAsync(cancellationToken);

            var stockByProduct = await db.VehicleProductStocks
                .Where(s => s.VehicleId == trip.VehicleId)
                .ToDictionaryAsync(s => s.ProductId, cancellationToken);

            var vehicleStockProductIds = stockByProduct
                .Where(kv => kv.Value.BasicQuantityOnHand > 0 || kv.Value.PackagingQuantityOnHand > 0)
                .Select(kv => kv.Key);

            var productIds = soldByProduct.Keys
                .Union(loadedProductIds)
                .Union(vehicleStockProductIds)
                .Distinct()
                .ToList();
            if (productIds.Count == 0) return;

            var productMetadata = await db.Products
                .Where(p => productIds.Contains(p.Id))
                .Include(p => p.BasicUnit)
                .Include(p => p.PackagingUnit)
                .ToDictionaryAsync(p => p.Id, cancellationToken);

            var capturedAt = DateTime.UtcNow;

            foreach (var productId in productIds)
            {
                if (!productMetadata.TryGetValue(productId, out var product)) continue;

                stockByProduct.TryGetValue(productId, out var stock);
                var basicStart = stock?.BasicQuantityOnHand ?? 0;
                var packagingStart = stock?.PackagingQuantityOnHand ?? 0;

                soldByProduct.TryGetValue(productId, out var sold);
                var basicSold = sold?.BasicSold ?? 0;
                var packagingSold = sold?.PackagingSold ?? 0;
                var revenue = sold?.Revenue ?? 0;

                db.TrekkingTripStockSnapshots.Add(new Entities.TrekkingTripStockSnapshot
                {
                    TrekkingTripId = trip.Id,
                    ProductId = productId,
                    ProductName = product.Name,
                    BasicUnitName = product.BasicUnit?.Name,
                    PackagingUnitName = product.PackagingUnit?.Name,
                    BasicUnitPrice = product.BasicUnitPrice,
                    PackagingUnitPrice = product.PackagingUnitPrice,
                    BasicQtyAtStart = basicStart,
                    PackagingQtyAtStart = packagingStart,
                    BasicQtySold = basicSold,
                    PackagingQtySold = packagingSold,
                    BasicQtyRemaining = basicStart - basicSold,
                    PackagingQtyRemaining = packagingStart - packagingSold,
                    RevenueAmount = revenue,
                    CapturedAt = capturedAt
                });
            }
        }

        private async Task SyncVehicleStockOnCompletionAsync(Entities.TrekkingTrip trip, CancellationToken cancellationToken)
        {
            var deliveredByProduct = trip.Stops
                .SelectMany(s => s.Products)
                .Where(p => p.BasicQtyDelivered.HasValue && p.BasicQtyDelivered > 0)
                .GroupBy(p => p.ProductId)
                .Select(g => new
                {
                    ProductId = g.Key,
                    BasicDelivered = g.Sum(p => p.BasicQtyDelivered ?? 0),
                    PackagingDelivered = g.Sum(p => p.PackagingQtyDelivered ?? 0)
                })
                .ToList();

            if (deliveredByProduct.Count == 0) return;

            var productIds = deliveredByProduct.Select(d => d.ProductId).ToList();

            var stockRecords = await db.VehicleProductStocks
                .Where(s => s.VehicleId == trip.VehicleId && productIds.Contains(s.ProductId))
                .ToListAsync(cancellationToken);

            var now = DateTime.UtcNow;

            foreach (var delivery in deliveredByProduct)
            {
                var stock = stockRecords.FirstOrDefault(s => s.ProductId == delivery.ProductId);
                if (stock is null) continue;

                var basicDeducted = Math.Min(delivery.BasicDelivered, stock.BasicQuantityOnHand);
                var packagingDeducted = Math.Min(delivery.PackagingDelivered, stock.PackagingQuantityOnHand);

                stock.BasicQuantityOnHand = Math.Max(0, stock.BasicQuantityOnHand - delivery.BasicDelivered);
                stock.PackagingQuantityOnHand = Math.Max(0, stock.PackagingQuantityOnHand - delivery.PackagingDelivered);
                stock.UpdatedAt = now;

                db.VehicleStockLedger.Add(new VehicleStockLedger
                {
                    VehicleId = trip.VehicleId,
                    ProductId = delivery.ProductId,
                    ChangeType = StockChangeType.Reduction,
                    Source = StockChangeSource.TrekCompletion,
                    BasicQtyChange = basicDeducted,
                    PackagingQtyChange = packagingDeducted,
                    BasicBalanceAfter = stock.BasicQuantityOnHand,
                    PackagingBalanceAfter = stock.PackagingQuantityOnHand,
                    Reason = $"Trek {trip.TrekNumber} completed — {basicDeducted:0.###} units delivered",
                    ReferenceId = trip.Id,
                    AuthorStaffId = null,
                    RecordedAt = now
                });
            }
        }

        private async Task NotifyPendingReturnsAsync(Entities.TrekkingTrip trip, CancellationToken cancellationToken)
        {
            var pendingCount = trip.Stops
                .SelectMany(s => s.Returns)
                .Count(r => r.ApprovalStatus == ReturnApprovalStatus.Pending);

            if (pendingCount == 0) return;

            var creator = await db.StaffMembers
                .Where(s => s.ApplicationUser!.Id == trip.CreatedBy)
                .Select(s => new { s.Id, s.FullName, s.EmailAddress })
                .FirstOrDefaultAsync(cancellationToken);

            if (creator is null) return;

            var data = System.Text.Json.JsonSerializer.Serialize(new { trekId = trip.Id, trekNumber = trip.TrekNumber });
            _ = notifications.DispatchAsync(
                "PendingReturns",
                "Pending Returns",
                $"Trek {trip.TrekNumber} has been completed with {pendingCount} pending return(s) awaiting your approval.",
                data,
                [creator.Id]);

            var frontendUrl = config["SiteSettings:FrontendUrl"] ?? string.Empty;
            var appName = config["SiteSettings:AppName"] ?? "Proh Pharmacy";
            var supportEmail = config["EmailSettings:SupportEmail"] ?? string.Empty;

            _ = email.SendPendingReturnsNotificationAsync(creator.EmailAddress, new PendingReturnsNotificationEmailModel
            {
                RecipientName = creator.FullName,
                TrekNumber = trip.TrekNumber ?? string.Empty,
                CompletedDate = DateTime.UtcNow.ToString("dd MMM yyyy"),
                PendingReturnCount = pendingCount,
                ReviewUrl = $"{frontendUrl}/treks/{trip.Id}",
                AppName = appName,
                SupportEmail = supportEmail
            });
        }
    }
}

public class CompleteTrekByDriverTokenEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapPost("api/v1/treks/driver/{token:guid}/complete",
            async (Guid token, ISender sender) =>
            {
                var result = await sender.Send(new CompleteTrekByDriverToken.Command { Token = token });
                return result.IsFailure
                    ? Results.UnprocessableEntity(result.Error)
                    : Results.Ok(result.Value);
            })
        .WithTags("Trekking")
        .WithGroupName(SwaggerDoc.SwaggerEndpointDefinitions.Trekking)
        .WithSummary("Mark the driver's trek as completed (driver portal)")
        .WithDescription("Marks the assigned trek as Completed and runs the full ledger sync — credit entries for payments received, debit entries for outstanding balances and product return refunds. Only allowed when the trek is InProgress. No request body required.")
        .Produces<TrekResponse>(200)
        .Produces<Error>(422)
        .AllowAnonymous();
    }
}
