using Carter;
using MediatR;
using Microsoft.EntityFrameworkCore;
using prohpharmacy_trekking_app.Database;
using prohpharmacy_trekking_app.Extensions;
using prohpharmacy_trekking_app.Features.Ledger.Entities;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Features.Trekking.Enums;
using prohpharmacy_trekking_app.Shared;
using static prohpharmacy_trekking_app.Features.Trekking.CreateTrek;

namespace prohpharmacy_trekking_app.Features.Trekking;

public static class CompleteTrekByDriverToken
{
    public class Command : IRequest<Result<TrekResponse>>
    {
        public Guid Token { get; set; }
    }

    internal sealed class Handler(AppDbContext db) : IRequestHandler<Command, Result<TrekResponse>>
    {
        public async Task<Result<TrekResponse>> Handle(Command request, CancellationToken cancellationToken)
        {
            await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken);
            try
            {
                var trip = await db.TrekkingTrips
                    .Include(t => t.Region)
                    .Include(t => t.Branch)
                    .Include(t => t.Driver)
                    .Include(t => t.SalesStaff)
                    .Include(t => t.Vehicle)
                    .Include(t => t.Stops)
                        .ThenInclude(s => s.Products)
                    .Include(t => t.Stops)
                        .ThenInclude(s => s.Returns)
                    .FirstOrDefaultAsync(t => t.DriverToken == request.Token, cancellationToken);

                if (trip is null)
                    return Result.Failure<TrekResponse>(Error.CreateNotFoundError("Trek not found. The token may be invalid."));

                if (trip.Status == TrekStatus.Completed)
                    return Result.Failure<TrekResponse>(Error.BadRequest("This trek is already marked as completed."));

                if (trip.Status == TrekStatus.Cancelled)
                    return Result.Failure<TrekResponse>(Error.BadRequest("A cancelled trek cannot be completed."));

                if (trip.Status != TrekStatus.InProgress)
                    return Result.Failure<TrekResponse>(Error.BadRequest("Only an in-progress trek can be marked as completed."));

                trip.Status = TrekStatus.Completed;
                trip.UpdatedAt = DateTime.UtcNow;

                await SyncLedgerOnCompletionAsync(trip, cancellationToken);

                await db.SaveChangesAsync(cancellationToken);
                await transaction.CommitAsync(cancellationToken);

                return Result.Success(CreateTrek.Handler.ToResponse(
                    trip,
                    trip.Region?.Name ?? string.Empty,
                    trip.Branch?.Name,
                    trip.Driver?.FullName ?? string.Empty,
                    trip.SalesStaff?.FullName,
                    trip.Vehicle?.DisplayName ?? string.Empty,
                    []));
            }
            catch
            {
                await transaction.RollbackAsync(cancellationToken);
                throw;
            }
        }

        private async Task SyncLedgerOnCompletionAsync(Entities.TrekkingTrip trip, CancellationToken cancellationToken)
        {
            var stopIds = trip.Stops.Select(s => s.Id).ToList();

            var existing = await db.CustomerLedgerEntries
                .Where(e => e.TrekkingTripStopId.HasValue
                    && stopIds.Contains(e.TrekkingTripStopId.Value)
                    && e.IsAutoGenerated)
                .ToListAsync(cancellationToken);
            db.CustomerLedgerEntries.RemoveRange(existing);

            var now = DateTime.UtcNow;
            var attributedStaffId = trip.SalesStaffId ?? trip.DriverStaffId;

            foreach (var stop in trip.Stops)
            {
                var paymentGroups = stop.Products
                    .Where(p => p.AmtPaid > 0 && p.PaymentMethod.HasValue)
                    .GroupBy(p => p.PaymentMethod!.Value);

                foreach (var group in paymentGroups)
                {
                    var amtPaid = group.Sum(p => p.AmtPaid ?? 0);
                    db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Credit,
                        Amount = amtPaid,
                        PaymentMethod = group.Key.ToString(),
                        Description = $"Payment received ({group.Key}) — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = attributedStaffId,
                        CreatedAt = now
                    });
                }

                var balance = stop.Products.Sum(p => p.Balance ?? 0);
                if (balance > 0)
                    db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Debit,
                        Amount = balance,
                        Description = $"Outstanding balance — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = attributedStaffId,
                        CreatedAt = now
                    });

                foreach (var ret in stop.Returns.Where(r => r.RefundAmount.HasValue && r.RefundAmount > 0))
                {
                    db.CustomerLedgerEntries.Add(new CustomerLedgerEntry
                    {
                        CustomerAccountId = stop.CustomerAccountId,
                        EntryType = LedgerEntryType.Debit,
                        Amount = ret.RefundAmount!.Value,
                        PaymentMethod = ret.RefundMethod?.ToString(),
                        Description = $"Product return refund — Trek {trip.TrekNumber}",
                        TrekkingTripId = trip.Id,
                        TrekkingTripStopId = stop.Id,
                        IsAutoGenerated = true,
                        RecordedAt = now,
                        CreatedByStaffId = attributedStaffId,
                        CreatedAt = now
                    });
                }
            }
        }
    }
}

public class CompleteTrekByDriverTokenEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapPost("api/v1/treks/driver/{token:guid}/complete",
            async (Guid token, ISender sender) =>
            {
                var result = await sender.Send(new CompleteTrekByDriverToken.Command { Token = token });
                return result.IsFailure
                    ? Results.UnprocessableEntity(result.Error)
                    : Results.Ok(result.Value);
            })
        .WithTags("Trekking")
        .WithGroupName(SwaggerDoc.SwaggerEndpointDefinitions.Trekking)
        .WithSummary("Mark the driver's trek as completed (driver portal)")
        .WithDescription("Marks the assigned trek as Completed and runs the full ledger sync — credit entries for payments received, debit entries for outstanding balances and product return refunds. Only allowed when the trek is InProgress. No request body required.")
        .Produces<TrekResponse>(200)
        .Produces<Error>(422)
        .AllowAnonymous();
    }
}
