using prohpharmacy_trekking_app.Features.Customers.Entities;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Features.Staff.Entities;
using prohpharmacy_trekking_app.Features.Trekking.Entities;

namespace prohpharmacy_trekking_app.Features.Ledger.Entities;

public class CustomerLedgerEntry
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid CustomerAccountId { get; set; }
    public LedgerEntryType EntryType { get; set; }
    public decimal Amount { get; set; }
    public string Description { get; set; } = string.Empty;
    public Guid? TrekkingTripId { get; set; }
    public Guid? TrekkingTripStopId { get; set; }
    public bool IsAutoGenerated { get; set; }
    public DateTime RecordedAt { get; set; }
    public Guid CreatedByStaffId { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    public CustomerAccount CustomerAccount { get; set; } = null!;
    public TrekkingTrip? TrekkingTrip { get; set; }
    public TrekkingTripStop? TrekkingTripStop { get; set; }
    public StaffMember CreatedBy { get; set; } = null!;
}
