using Carter;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using prohpharmacy_trekking_app.Database;
using prohpharmacy_trekking_app.Extensions;
using prohpharmacy_trekking_app.Features.Ledger.Entities;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Providers;
using prohpharmacy_trekking_app.Shared;

namespace prohpharmacy_trekking_app.Features.Ledger;

public static class AddLedgerEntry
{
    public class Command : IRequest<Result<LedgerEntryResponse>>
    {
        public Guid CustomerId { get; set; }
        public string EntryType { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Description { get; set; } = string.Empty;
        public DateTime? RecordedAt { get; set; }
    }

    public class LedgerEntryResponse
    {
        public Guid Id { get; set; }
        public string EntryType { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Description { get; set; } = string.Empty;
        public bool IsAutoGenerated { get; set; }
        public DateTime RecordedAt { get; set; }
        public string RecordedBy { get; set; } = string.Empty;
    }

    public class Validator : AbstractValidator<Command>
    {
        public Validator()
        {
            RuleFor(x => x.Amount).GreaterThan(0).WithMessage("Amount must be greater than 0.");
            RuleFor(x => x.Description).NotEmpty().MaximumLength(500);
            RuleFor(x => x.EntryType)
                .Must(v => Enum.TryParse<LedgerEntryType>(v, true, out _))
                .WithMessage("EntryType must be 'Debit' or 'Credit'.");
        }
    }

    internal sealed class Handler(AppDbContext db, AuthProvider auth)
        : IRequestHandler<Command, Result<LedgerEntryResponse>>
    {
        public async Task<Result<LedgerEntryResponse>> Handle(Command request, CancellationToken cancellationToken)
        {
            var customerExists = await db.CustomerAccounts
                .AnyAsync(a => a.Id == request.CustomerId, cancellationToken);

            if (!customerExists)
                return Result.Failure<LedgerEntryResponse>(Error.CreateNotFoundError("Customer not found."));

            if (!Guid.TryParse(auth.GetUserId(), out var staffId))
                return Result.Failure<LedgerEntryResponse>(Error.BadRequest("Authenticated user ID is invalid."));

            Enum.TryParse<LedgerEntryType>(request.EntryType, true, out var entryType);

            var now = DateTime.UtcNow;
            var entry = new CustomerLedgerEntry
            {
                CustomerAccountId = request.CustomerId,
                EntryType = entryType,
                Amount = request.Amount,
                Description = request.Description.Trim(),
                IsAutoGenerated = false,
                RecordedAt = request.RecordedAt ?? now,
                CreatedByStaffId = staffId,
                CreatedAt = now
            };

            db.CustomerLedgerEntries.Add(entry);
            await db.SaveChangesAsync(cancellationToken);

            var recorderName = await db.StaffMembers
                .Where(s => s.Id == staffId)
                .Select(s => s.FullName)
                .FirstOrDefaultAsync(cancellationToken) ?? string.Empty;

            return Result.Success(new LedgerEntryResponse
            {
                Id = entry.Id,
                EntryType = entry.EntryType.ToString(),
                Amount = entry.Amount,
                Description = entry.Description,
                IsAutoGenerated = false,
                RecordedAt = entry.RecordedAt,
                RecordedBy = recorderName
            });
        }
    }
}

public class AddLedgerEntryEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapPost("api/v1/customers/{customerId:guid}/ledger",
            async (Guid customerId, AddLedgerEntry.Command command, ISender sender) =>
            {
                command.CustomerId = customerId;
                var result = await sender.Send(command);
                return result.IsFailure
                    ? Results.UnprocessableEntity(result.Error)
                    : Results.Created($"api/v1/customers/{customerId}/ledger", result.Value);
            })
            .WithTags("Customers")
            .WithGroupName(SwaggerDoc.SwaggerEndpointDefinitions.Customers)
            .WithSummary("Add ledger entry")
            .WithDescription("Manually record a Debit or Credit entry on a customer's ledger.")
            .Produces<AddLedgerEntry.LedgerEntryResponse>(201)
            .Produces<Error>(404)
            .Produces<Error>(422)
            .RequireAuthorization();
    }
}
