using Carter;
using MediatR;
using Microsoft.EntityFrameworkCore;
using prohpharmacy_trekking_app.Database;
using prohpharmacy_trekking_app.Extensions;
using prohpharmacy_trekking_app.Features.Ledger.Enums;
using prohpharmacy_trekking_app.Shared;

namespace prohpharmacy_trekking_app.Features.Ledger;

public static class GetCustomerLedger
{
    public class Query : IRequest<Result<LedgerResponse>>
    {
        public Guid CustomerId { get; set; }
        public LedgerEntryType? EntryType { get; set; }
        public int? PageNumber { get; set; }
        public int? PageSize { get; set; }
    }

    public class LedgerResponse
    {
        public Guid CustomerId { get; set; }
        public decimal TotalDebits { get; set; }
        public decimal TotalCredits { get; set; }
        public decimal CurrentBalance { get; set; }
        public int Page { get; set; }
        public int PageSize { get; set; }
        public int TotalCount { get; set; }
        public int TotalPages { get; set; }
        public List<LedgerEntryResponse> Entries { get; set; } = [];
    }

    public class LedgerEntryResponse
    {
        public Guid Id { get; set; }
        public string EntryType { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string? PaymentMethod { get; set; }
        public string Description { get; set; } = string.Empty;
        public Guid? TrekId { get; set; }
        public string? TrekNumber { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime RecordedAt { get; set; }
        public string RecordedBy { get; set; } = string.Empty;
    }

    internal sealed class Handler(AppDbContext db)
        : IRequestHandler<Query, Result<LedgerResponse>>
    {
        public async Task<Result<LedgerResponse>> Handle(Query request, CancellationToken cancellationToken)
        {
            var customerExists = await db.CustomerAccounts
                .AnyAsync(a => a.Id == request.CustomerId, cancellationToken);

            if (!customerExists)
                return Result.Failure<LedgerResponse>(Error.CreateNotFoundError("Customer not found."));

            var totalDebits = await db.CustomerLedgerEntries
                .Where(e => e.CustomerAccountId == request.CustomerId && e.EntryType == LedgerEntryType.Debit)
                .SumAsync(e => (decimal?)e.Amount, cancellationToken) ?? 0;

            var totalCredits = await db.CustomerLedgerEntries
                .Where(e => e.CustomerAccountId == request.CustomerId && e.EntryType == LedgerEntryType.Credit)
                .SumAsync(e => (decimal?)e.Amount, cancellationToken) ?? 0;

            var baseQuery = db.CustomerLedgerEntries
                .Include(e => e.TrekkingTrip)
                .Include(e => e.CreatedBy)
                .Where(e => e.CustomerAccountId == request.CustomerId)
                .AsNoTracking();

            if (request.EntryType.HasValue)
                baseQuery = baseQuery.Where(e => e.EntryType == request.EntryType.Value);

            var totalCount = await baseQuery.CountAsync(cancellationToken);
            var page = Math.Max(1, request.PageNumber ?? 1);
            var pageSize = Math.Clamp(request.PageSize ?? 20, 1, 100);
            var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);

            var entries = await baseQuery
                .OrderByDescending(e => e.RecordedAt)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .Select(e => new LedgerEntryResponse
                {
                    Id = e.Id,
                    EntryType = e.EntryType.ToString(),
                    Amount = e.Amount,
                    PaymentMethod = e.PaymentMethod,
                    Description = e.Description,
                    TrekId = e.TrekkingTripId,
                    TrekNumber = e.TrekkingTrip != null ? e.TrekkingTrip.TrekNumber : null,
                    IsAutoGenerated = e.IsAutoGenerated,
                    RecordedAt = e.RecordedAt,
                    RecordedBy = e.CreatedBy.FullName
                })
                .ToListAsync(cancellationToken);

            return Result.Success(new LedgerResponse
            {
                CustomerId = request.CustomerId,
                TotalDebits = totalDebits,
                TotalCredits = totalCredits,
                CurrentBalance = totalDebits - totalCredits,
                Page = page,
                PageSize = pageSize,
                TotalCount = totalCount,
                TotalPages = totalPages,
                Entries = entries
            });
        }
    }
}

public class GetCustomerLedgerEndpoint : ICarterModule
{
    public void AddRoutes(IEndpointRouteBuilder app)
    {
        app.MapGet("api/v1/customers/{customerId:guid}/ledger",
            async (Guid customerId, ISender sender,
                [Microsoft.AspNetCore.Mvc.FromQuery] string? entryType,
                [Microsoft.AspNetCore.Mvc.FromQuery] int? pageNumber,
                [Microsoft.AspNetCore.Mvc.FromQuery] int? pageSize) =>
            {
                var type = Enum.TryParse<LedgerEntryType>(entryType, true, out var parsed)
                    ? parsed : (LedgerEntryType?)null;

                var result = await sender.Send(new GetCustomerLedger.Query
                {
                    CustomerId = customerId,
                    EntryType = type,
                    PageNumber = pageNumber,
                    PageSize = pageSize
                });

                return result.IsFailure
                    ? Results.NotFound(result.Error)
                    : Results.Ok(result.Value);
            })
            .WithTags("Customers")
            .WithGroupName(SwaggerDoc.SwaggerEndpointDefinitions.Customers)
            .WithSummary("Get customer ledger")
            .WithDescription("Returns paginated ledger entries with running totals and current outstanding balance. Filter by entryType: Debit or Credit.")
            .Produces<GetCustomerLedger.LedgerResponse>(200)
            .Produces<Error>(404)
            .RequireAuthorization();
    }
}
